name: ML Pipeline

on:
  workflow_dispatch:  # This event allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # You can change this to your preferred Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Replace with your dependency installation command

    - name: Run your ML pipeline
      run: |
        ./run.sh  # Replace with the command to run your ML pipeline
